OPEN_AI_KEY="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"

PATH_ORIGINAL_DATA="data/Articles_2023.json"
PATH_GT_DATA="data/articles_categories_their_matched_companies.csv"
PATH_NOT_PREPROCESSED="data/chosen_articles.txt"
PATH_4O="data/chosen_articles_cleaned_4o.txt"
PATH_REGEX="data/chosen_articles_cleaned_regex.txt"
PATH_HUMAN="data/chosen_articles_cleaned_by_me.txt"